version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    environment:
      - TZ=America/Fortaleza
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports: 
      - 25672:25672 # (erlang) communication between the nodes and CLI tool
      - 15672:15672 # communication with the web management API 
      - 5672:5672
    # volumes:
    #   # data persistence
    #   - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
    restart: always
    networks:
        - rabbitmq_nodejs

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
      - TZ=America/Fortaleza
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on: 
      - rabbitmq
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- npm run start:dev'
    networks:
        - rabbitmq_nodejs

networks:
  rabbitmq_nodejs:
    driver: bridge