version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq_management
    environment:
      - TZ=America/Fortaleza
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports: 
      - 25672:25672 # (erlang) communication between the nodes and CLI tool
      - 15672:15672 # communication with the web management API 
    volumes:
      # data persistence
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/

    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
      - TZ=America/Fortaleza

    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on: 
      - rabbitmq
volumes:
  logs-folder:
    name: rabbitmq.log
    driver: local